### ISSUE TITLE
When will the code for this project be released?

### ISSUE THREAD

**Issue by LLLLLLoki** [dki-lab/Pangu#1]
Just read the paper, it's very creative, I can't wait to see how it works.

**Comment by feng-1985** [comment]
add paper link: https://arxiv.org/abs/2212.09736

**Comment by PrayushiFaldu** [comment]
@feng-1985 Any idea about the code release?

**Comment by entslscheia** [comment]
@LLLLLLoki @PrayushiFaldu 
We are working on releasing the code, but we cannot do it right now due to some policy. Please stay tuned

**Comment by entslscheia** [comment]
We've already released our code for the ACL paper.
Meanwhile, we are working hard to release the Pangu library that can be easily used for far-ranging grounded language understanding tasks.
