### ISSUE TITLE
关于一些数据文件的获取方式

### ISSUE THREAD

**Issue by willer-lu** [dki-lab/Pangu#19]
如何获取对应于这些数据集的训练集的el_results?       
例如对于webqsp的测试集而言，其对应的文件为
`/transfer_freebase/el_results/webqsp_test_elq.json`    
如何从它的训练集获取对应文件？

**Comment by entslscheia** [comment]
Hi,

For entity linking results using ELQ, we directly use the results provided by TIARA (https://aclanthology.org/2022.emnlp-main.555/). For more details on ELQ, you may check https://aclanthology.org/2020.emnlp-main.522/

Best,
Yu
