### ISSUE TITLE
for questions without entities, what is the initial plan?

### ISSUE THREAD

**Issue by HaishuoFang** [dki-lab/Pangu#2]
Hello,

Thanks for your wonderful work! One thing I am thinking is such methods always need an initial plan. But for those questions without entities, how can this method work? Thank you

Best,
Haishuo

**Comment by entslscheia** [comment]
Hi Haishuo,

Thanks for your interest in our work! For questions without entities (mainly for questions with programs like (ARGMAX class attribute) from GrailQA), we use a set of predicted answer types (inherited from ArcaneQA) as the initial plans. Note that, for majority of the questions, where we do have entities identified, we will not need this step.

We are working tirelessly to release Pangu library. Please stay tuned! Thanks for your patience.

Best,
Yu

**Comment by HaishuoFang** [comment]
Thank you! Yu
