### ISSUE TITLE
Problem with the inference based on the saved model.

### ISSUE THREAD

**Issue by czh17** [dki-lab/Pangu#20]
Hi，
thank you for sharing your outstanding work.
I'm having problems with direct inference using the model in [trained_models.md](https://github.com/dki-lab/Pangu/blob/main/trained_models.md).
Here's the command I ran:
```
PYTHONHASHSEED=23 python run.py \
    predict \
    trained_model/grailqa_bert_base.tar.gz \
    data/grailqa_v1.0_dev.json \
    --include-package \
    new_model.bottom_up_parser \
    --include-package \
    new_model.bottom_up_parser_reader \
    --include-package \
    utils.huggingface_interface \
    --output-file \
    predictions.txt \
    --use-dataset-reader \
    --cuda 0 \
    -o \
    "{'model': {'infer': true}, 'validation_dataset_reader': {'infer': true, 'perfect_entity_linking': false}}"
```
I got the following outputs:
![problem_one](https://github.com/dki-lab/Pangu/assets/26423077/62a1668d-221f-4adf-9c79-00ecb1839bde)
Is there something wrong with the command I'm running?
I manually downloaded the required bert-based-uncased model. I got the following output:
![problem_two](https://github.com/dki-lab/Pangu/assets/26423077/88e63c10-bea4-4f27-9aad-8fad874913a7)

**Comment by entslscheia** [comment]
Sorry for the late response.
The first error seems to be a network issue that Huggingface might be blocked in your local ip.
Regarding the second issue, I think I've manually removed all `using_hf` parameters during code cleaning since it's not useful, but it's likely that I can miss one. You can just ignore this issue by adding a dummy using_hf parameter to the BottomUpParser class.

**Comment by czh17** [comment]
Thank you for getting back to me. 
The F1 reproduced on the GrailQA dev dataset is 81.69. 
Someone behind “The Great Wall” can download the BERT model locally and point the address in the code to the BERT model. Then add a dummy using_hf parameter to the BottomUpParser class.
