### ISSUE TITLE
Multi GPU training.

### ISSUE THREAD

**Issue by PrayushiFaldu** [dki-lab/Pangu#7]
Does the current codebase support distributed training? The code stuck at the beginning when I tried distributed training. Is it because the validation metric is avg EM? 
Please point to the changes in the code for distributed training.

**Comment by entslscheia** [comment]
Yeah, for distributed training, you can directly uncomment the [distributed field](https://github.com/dki-lab/Pangu/blob/32ed3731b72cb58a74c6325904902da492da5ecc/acl_configs/grail_train.jsonnet#L72-L74) in config files.

It worked fine on our server with A6000 GPU, however, I did notice that sometimes the code may stuck at the beginning when using 2080Ti cards. This might be a hardware- or coda-related issue.
