### ISSUE TITLE
CodeX code

### ISSUE THREAD

**Issue by 233function** [dki-lab/Pangu#8]
你好，能把CodeX部分的代码上传上来么

**Comment by entslscheia** [comment]
yeah sure. I plan to clean and upload that part today

**Comment by gourango01** [comment]
Any update on this?

**Comment by entslscheia** [comment]
Please see the code for OpenAI API here: https://github.com/dki-lab/Pangu/tree/main/openai_eval
Codex is down, but you can still try it with `text-davinci`. It can be slow if you only have one api key
